#!/usr/bin/perl
use strict;
use warnings;
use diagnostics;
use File::Spec;

my $workdir = "";
my $abs_path = File::Spec->rel2abs( $workdir ) ;
print "$#ARGV\n"; 
if (-d $ARGV[0] && $#ARGV == 0) {
  my $workdir = $ARGV[0];
  print "starting at $abs_path\n";
}
else {
  print "you must pass exactly one directory as an argument to this script\n";
  die "$!\n";
}


