#!/bin/bash
IFS='
'
toplevel="$1"

find_subdirectories () {
  cd "$1"
  while [[ -n $(find . -maxdepth 1 -mindepth 1 -type d) ]]; do
    pwd
    cd $(find . -maxdepth 1 -mindepth 1 -type d)
  done
}

find_subdirectories $toplevel
