#!/bin/bash

IFS='
'
root_dir=$1

cd $root_dir

subdircheck () {
while $(find . -maxdepth 1 -mindepth 1); do
  subdircheck
done

# for ordner in subdir_check $root_dir; do
#   echo $ordner
# done







#  - check, ob es weitere directories gibt
#
#   wenn ja: 
#      
#   - der reihenfolge nach in alle dirs gehen, dort (von anfang an, enter recursion)
#
#   wenn nein: (gucken, ob's mp3s gibt usw.)
