#!/bin/bash

##### VARIABLEN: IFS, Farben usw,
OLDIFS="$IFS"
IFS='
'

RED='\033[0;31m'
NC='\033[0m'

root_dir="$1"

##### FUNKTIONEN
## gucken, ob es im Ordner Audiodateien hat
check_for_audio () {
  exiftool -s -S -Mimetype $1 | grep audio
}

## gucken, ob's im Ordner weitere Unterordner gibt
checksb () {
  find $1 -mindepth 1 -maxdepth 1 -type d
}

## in Unterverzeichnisse absteigen und gucken, ob's Audiodateien gibt
checksub () {
if [[ -n "$(checksb $1)" ]]; then		## wenn der Rückgabewert nicht leer ist, sind Unterverzeichnisse vorhanden
  echo "subdir found in $1, descending"		
  for i in $(checksb $1); do			## jedes Unterverzeichnis angucken und ggf. weiter absteigen
    checksub "$i"
  done

else

  echo "$i is a leaf node"			## wenn keine Unterverzeichnisse da sind, ist es ein Leaf
    if [[ $(check_for_audio "$i") ]]; then	## nachschauen, ob im Leaf Audiodateien sind
      echo "which contains audiofiles"
      

    else

      echo -e "${RED}that has no audiofiles in it${NC}"
    fi
fi
}



##### MAIN
checksub $root_dir


